#!/usr/bin/env python3
"""Regenerate the reviews wall in index.html from reviews.json.

Usage:  python tools/build-reviews.py

Reads reviews.json, renders one card per review, splits them across two
rows (row 1 scrolls left, row 2 scrolls right) and writes the result
between the REVIEWS:START / REVIEWS:END markers in index.html.

Each row's cards are emitted TWICE. The marquee animates the track from
0 to -50%, so the second copy is what makes the loop seamless — and the
per-card spacing has to be margin-right rather than flex gap, otherwise
-50% lands mid-gap and the join visibly jumps.
"""

import html
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "reviews.json")
PAGE = os.path.join(ROOT, "index.html")
START = "    <!-- REVIEWS:START — generated by tools/build-reviews.py, do not edit by hand -->"
END = "    <!-- REVIEWS:END -->"


def mark_html(r):
    """The brand mark at the head of the footer.

    Every card gets one: the logo file where a store has one, otherwise the
    store name set as a wordmark. That is the same fallback the OE demo's
    BrandStrip uses, and it means no card is left with a blank slot.
    """
    if r.get("logo"):
        return '<img class="cp-rw__mark" src="{src}" alt="{alt}">'.format(
            src=html.escape(r["logo"], quote=True),
            alt=html.escape(r.get("logoAlt") or r["name"], quote=True),
        )
    # inner span so the outer box can centre while the text still clamps -
    # a few store names run past one line at this width
    return '<span class="cp-rw__mark cp-rw__mark--word"><span>{name}</span></span>'.format(
        name=html.escape(r["name"])
    )


QUOTE_OPEN = (
    '<svg class="cp-rw__q" width="26" height="20" viewBox="0 0 26 20" fill="#252525" aria-hidden="true">'
    '<path d="M0 20V11.6C0 5.6 3.4 1.2 9.6 0l1.2 3.2C7 4.4 5.2 6.6 5.2 9.2h4.2V20H0Z'
    'm14.8 0V11.6C14.8 5.6 18.2 1.2 24.4 0L25.6 3.2c-3.8 1.2-5.6 3.4-5.6 6h4.2V20h-9.4Z"/></svg>'
)
QUOTE_CLOSE = (
    '<svg class="cp-rw__q cp-rw__q--end" width="22" height="17" viewBox="0 0 26 20" fill="#252525" aria-hidden="true">'
    '<path d="M26 0v8.4c0 6-3.4 10.4-9.6 11.6l-1.2-3.2c3.8-1.2 5.6-3.4 5.6-6h-4.2V0H26Z'
    'M11.2 0v8.4c0 6-3.4 10.4-9.6 11.6L.4 16.8c3.8-1.2 5.6-3.4 5.6-6H1.8V0h9.4Z"/></svg>'
)


def card(r):
    country = r.get("country") or ""
    return (
        '        <figure class="cp-rw__card">\n'
        "          {qopen}\n"
        '          <blockquote class="cp-rw__text">{quote}</blockquote>\n'
        "          {qclose}\n"
        '          <figcaption class="cp-rw__foot">\n'
        '            <span class="cp-rw__who">{mark}{role}</span>\n'
        '            <span class="cp-rw__meta">{date}{country}</span>\n'
        "          </figcaption>\n"
        "        </figure>"
    ).format(
        qopen=QUOTE_OPEN,
        qclose=QUOTE_CLOSE,
        quote=html.escape(r["quote"]),
        role=('<span class="cp-rw__role">%s</span>' % html.escape(r["role"])) if r.get("role") else "",
        date=('<span class="cp-rw__date">%s</span>' % html.escape(r["date"])) if r.get("date") else "",
        mark=mark_html(r),
        country=('<span class="cp-rw__country">%s</span>' % html.escape(country)) if country else "",
    )


def row(reviews, direction):
    cards = "\n".join(card(r) for r in reviews)
    # emitted twice — the second set is the seamless wrap-around
    return (
        '      <div class="cp-rw__track cp-rw__track--{d}">\n{cards}\n{cards}\n      </div>'
    ).format(d=direction, cards=cards)


def lead_with_india(reviews):
    """Put the reviews that name Mohit first, then the Indian stores.

    This is the India page, so the wall opens on the team a merchant here
    would be talking to and on stores they would recognise. Entries with no
    country ride with the India group - most of them are Indian brands. The
    international reviews come last. Order within each group is unchanged,
    so all three stay newest-first.
    """
    mohit = [r for r in reviews if "Mohit" in r["quote"]]
    rest = [r for r in reviews if "Mohit" not in r["quote"]]
    india = [r for r in rest if not r.get("country") or r["country"] == "India"]
    intl = [r for r in rest if r.get("country") and r["country"] != "India"]
    print("leading with %d Mohit review(s), then %d India, then %d international"
          % (len(mohit), len(india), len(intl)))
    return mohit + india + intl


def main():
    with open(DATA, encoding="utf-8") as fh:
        reviews = json.load(fh)["reviews"]

    if not reviews:
        sys.exit("reviews.json has no entries")

    reviews = lead_with_india(reviews)

    # alternate so both rows stay balanced however many reviews there are
    top = reviews[0::2]
    bottom = reviews[1::2] or top

    block = "\n".join([
        START,
        '    <div class="cp-rw">',
        row(top, "left"),
        "    </div>",
        '    <div class="cp-rw">',
        row(bottom, "right"),
        "    </div>",
        END,
    ])

    with open(PAGE, encoding="utf-8", newline="") as fh:
        page = fh.read()

    nl = "\r\n" if "\r\n" in page else "\n"
    if START not in page or END not in page:
        sys.exit("markers not found in index.html — add REVIEWS:START/END first")

    i = page.index(START)
    j = page.index(END) + len(END)
    page = page[:i] + block.replace("\n", nl) + page[j:]

    with open(PAGE, "w", encoding="utf-8", newline="") as fh:
        fh.write(page)

    print("wrote %d reviews — %d in the top row, %d in the bottom" % (len(reviews), len(top), len(bottom)))


if __name__ == "__main__":
    main()
